name: pyinstaller

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build_linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip install -r requirements.txt
    - name: Build package
      run: |
        ./build.sh
        cd fastanalyzer # Build not working in outer dir ?!
        python -m PyInstaller fastanalyzer.py --noconsole --name="FastAnalyzer" #--icon=assets/images/icon.ico
    - name: Linux artefact
      uses: actions/upload-artifact@v3
      with:
        name: FastAnalyzer_linux
        path: ./fastanalyzer/dist/FastAnalyzer/

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        rm -f /usr/local/bin/2to3*
        rm -f /usr/local/bin/idle3*
        rm -f /usr/local/bin/pydoc3*
        rm -f /usr/local/bin/python3*
        rm -f /usr/local/opt/go/bin/go*
        rm -f /usr/local/bin/go*
        rm -rf /usr/local/lib/node*
        brew update -q -f
        brew upgrade -q -f
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip install -r requirements.txt
    - name: Build package
      run: |
        ./build.sh
        cd fastanalyzer # Build not working in outer dir ?!
        python -m PyInstaller fastanalyzer.py --noconsole --name="FastAnalyzer" --noconsole --onedir --windowed #--icon=assets/images/icon.ico
        hdiutil create -volname FastAnalyzer -srcfolder dist/FastAnalyzer.app -ov -format UDZO dist/FastAnalyzer.dmg
    - name: Mac artefact
      uses: actions/upload-artifact@v3
      with:
        name: FastAnalyzer_macos
        path: ./fastanalyzer/dist/FastAnalyzer.dmg

  build_windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip install -r requirements.txt
    - name: Build package
      shell: bash
      run: |
        ./build.sh
        cd fastanalyzer # Build not working in outer dir ?!
        python -m PyInstaller fastanalyzer.py --noconsole --name="FastAnalyzer" --noconsole #--icon=assets/images/icon.ico
    - name: Windows artefact
      uses: actions/upload-artifact@v3
      with:
        name: FastAnalyzer_windows
        path: ./fastanalyzer/dist/FastAnalyzer/
