name: pyinstaller

on:
  push:
    branches: [ master ]

jobs:

  build_linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip install -r requirements.txt
    - name: Build package
      run: |
        ./build.sh
        python -m PyInstaller src/fastanalyzer.py --onefile --noconsole --name="FastAnalyzer" #--icon=assets/images/icon.ico
    - name: Linux artefact
      uses: actions/upload-artifact@v3
      with:
        name: FastAnalyzer_linux
        path: ./dist/FastAnalyzer

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip install -r requirements.txt
    - name: Build package
      run: |
        ./build.sh
        python -m PyInstaller src/fastanalyzer.py --onefile --noconsole --name="FastAnalyzer" --noconsole #--icon=assets/images/icon.ico
    - name: Mac artefact
      uses: actions/upload-artifact@v3
      with:
        name: FastAnalyzer_macos
        path: ./dist/FastAnalyzer.app
        
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip install -r requirements.txt
    - name: Build package
      shell: bash
      run: |
        ./build.sh
        python -m PyInstaller src/fastanalyzer.py --onefile --noconsole --name="FastAnalyzer" --noconsole #--icon=assets/images/icon.ico 
    - name: Windows artefact
      uses: actions/upload-artifact@v3
      with:
        name: FastAnalyzer_windows
        path: ./dist/FastAnalyzer.exe
